# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: On OS ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu, macOs, windows]
    runs-on: "${{matrix.os}}-latest"
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: yarn test:all
